buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.9.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects { subproject ->
    subproject.tasks.withType(JavaCompile).configureEach { task ->
        task.options.compilerArgs.removeAll(["-Werror"])
        if (!task.options.compilerArgs.contains("-Xlint:-options")) {
            task.options.compilerArgs << "-Xlint:-options"
        }
    }
}
